## Arithmetic Operations

In [1]:
import numpy as np 

In [2]:
var = np.array([1,2,3,4])
add = var + 3
print(add)

[4 5 6 7]


In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
sum = arr1 + arr2
print(sum)

[ 6  8 10 12]


**add()**

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
sum = np.add(arr1, arr2)
print(sum)

[ 6  8 10 12]


In [5]:
a = np.array([1,2,3,4])
diff = a - 3
print(diff)

[-2 -1  0  1]


In [6]:
b = np.array([5,6,7,8])
c = np.array([1,4,5,7])
sub = b - c
print(sub)

[4 2 2 1]


**subtract()**

In [7]:
b = np.array([5,6,7,8])
c = np.array([1,4,5,7])
sub = np.subtract(b,c)
print(sub)

[4 2 2 1]


In [8]:
a1 = np.array([1,2,3,4])
mod = a1 % 3
print(mod)

[1 2 0 1]


**mod()**

In [9]:
a1 = np.array([1,2,3,4])
mod = np.mod(a1, 3)
print(mod)

[1 2 0 1]


In [10]:
x = np.array([2,5,6,8])
y = x**2
print(y)

[ 4 25 36 64]


**power()**

In [11]:
x = np.array([2,5,6,8])
y = np.power(x, 2)
print(y)

[ 4 25 36 64]


**reciprocal()**

In [12]:
m = np.array([4.0,6.0,8.0,9.0])
r = np.reciprocal(m)
print(r)

[0.25       0.16666667 0.125      0.11111111]


**multiply()**

In [13]:
m1 = np.array([2,3,4,5])
m2 = np.array([3,5,6,8])
multi = np.multiply(m1, m2)
print(multi)

[ 6 15 24 40]


**divide()**

In [14]:
d1 = np.array([14,19,24,30])
d2 = np.array([7, 4, 6, 7])
div = np.divide(d1, d2)
print(div)

[2.         4.75       4.         4.28571429]
