## Arithmetic Operations in 2-D array

In [1]:
# Sum
import numpy as np
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[5,6,7,8], [2,4,7,0]])
sum = np.add(arr1, arr2)
print(sum)

[[ 6  8 10 12]
 [ 7 10 14  8]]


In [2]:
# Subtraction
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[5,6,7,8], [2,4,7,0]])
sub = np.subtract(arr1, arr2)
print(sub)

[[-4 -4 -4 -4]
 [ 3  2  0  8]]


In [3]:
# Multiplication
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[5,6,7,8], [2,4,7,0]])
multi = np.multiply(arr1, arr2)
print(multi)

[[ 5 12 21 32]
 [10 24 49  0]]


In [4]:
# Division
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[5,6,7,8], [2,4,7,1]])
div = np.divide(arr1, arr2)
print(div)

[[0.2        0.33333333 0.42857143 0.5       ]
 [2.5        1.5        1.         8.        ]]


In [5]:
# Reciprocal
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
rec = np.reciprocal(arr1)
print(rec)

[[1 0 0 0]
 [0 0 0 0]]
