## Arithmetic functions in numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([3,6,8,9,1,4])

#np.min() - to find the minimum element
print("Minimum :",np.min(arr))

#np.max() - to find the maximum element
print("Maximum :", np.max(arr))

Minimum : 1
Maximum : 9


In [3]:
arr = np.array([3,6,8,9,1,4])

#np.argmin() - to find the position of minimum element
print("Position of minimum :", np.argmin(arr))

#np.argmax() - to find the positon of maximum element
print("Position of maximum :",np.argmax(arr))

Position of minimum : 4
Position of maximum : 3


In [4]:
arr1 = np.array([[2,1,3], [9,5,6]])
print(np.min(arr1, axis=1))

[1 5]


In [5]:
arr1 = np.array([[2,1,3], [9,5,6]])
print(np.min(arr1, axis=0))

[2 1 3]


In [6]:
arr2 = np.array([2,9,144,1,7])

#np.sqrt() - to find the square root of the elements in an array
print(np.sqrt(arr2))

[ 1.41421356  3.         12.          1.          2.64575131]


In [7]:
arr3 = np.array([1,2,3])

#np.sin() - to find the sin value
print(np.sin(arr3))

#np.cos() - to find the cos value
print(np.cos(arr3))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [8]:
arr4 = np.array([4,6,7])

#np.cumsum() - calculates the cumulative sum of elements in an array
print(np.cumsum(arr4))

[ 4 10 17]
