# Array Creation : Intrinsic numpy array creation objects

In [1]:
import numpy as np

In [2]:
# zeros : 
zeros = np.zeros((2,5)) # It will give an array of zeros of size (2,5)

In [3]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
zeros.dtype

dtype('float64')

In [5]:
zeros.shape

(2, 5)

In [6]:
zeros.size

10

In [7]:
# arange :
rng = np.arange(15)

In [8]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# linspace :
lspace = np.linspace(1,5,12) # It will give 12 elements from 1 to 5 with equal spacing

In [10]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [11]:
lspace1 = np.linspace(1,4,4) #  It will give 4 elements from 1 to 4 with equal spacing

In [12]:
lspace1

array([1., 2., 3., 4.])

In [13]:
# empty :
emp = np.empty((4,6)) # It gives random elements

In [14]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 4.45055939e-308, 1.33511562e-306],
       [1.42419938e-306, 7.56603881e-307, 8.45603440e-307,
        3.56043054e-307, 1.60219306e-306, 6.23059726e-307],
       [1.06811422e-306, 3.56043054e-307, 1.37961641e-306,
        1.05695167e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 8.01097889e-307, 5.11766988e-307]])

In [15]:
# empty_like :
emp_like = np.empty_like(lspace1)

In [16]:
emp_like

array([1., 2., 3., 4.])

In [17]:
#  identity :
ide = np.identity(45) # It will give an identity matrix of 45 * 45

In [18]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [19]:
ide.shape

(45, 45)

In [20]:
arr = np.arange(99)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
# reshape :
arr.reshape(3, 33) # Reshape the array into 3 * 33

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
# arr = reshape(3, 31), it will give error because 3*33 will contain 93 elements but we have 99 elements in our array named arr

In [24]:
arr # not changed

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr = arr.reshape(3,33) # Now it will change

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
# ravel : 
arr = arr.ravel() # It will convert to 1-D array

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.shape # It will now give the size of 1-D array

(99,)