In [1]:
import numpy as np

In [11]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print()
print(arr1)
print()

arr2 = np.array([[1], [2], [3]])
print(arr2.shape)
print()
print(arr2)
print()

print("Addition of arr1 and arr2 :",arr1 + arr2)


(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

Addition of arr1 and arr2 : [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [14]:
x = np.array([[1], [2]])
print(x.shape)

y = np.array([[1,2,3], [1,2,3]])
print(y.shape)
print()
print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]
