In [1]:
import numpy as np

**where() - finds the position(s) of elments in an array**

In [2]:
arr = np.array([1,2,3,4,5,2,5,6,7])

x = np.where(arr == 2)
print(x)

y = np.where((arr%2) == 0)
print(y)

(array([1, 5]),)
(array([1, 3, 5, 7]),)


**searchsorted() - returns the indexx where the specified value would be inserted to maintain the search order**

In [3]:
arr = np.array([1,2,7,4,5,9,2,6])

x = np.searchsorted(arr, 4)
print(x)

x1 = np.searchsorted(arr, [5,6,7],  side = "left")
print(x1)

x2 = np.searchsorted(arr, [5,6,7],  side = "right")
print(x2)

2
[2 5 8]
[7 8 8]


**sort() - returns the sorted array**

In [4]:
# 1-D Array
arr1 = np.array([24,6,12,0,8,1,32])
print(np.sort(arr1))

[ 0  1  6  8 12 24 32]


In [5]:
arr2 = np.array(["b", "x", "c", "s", "m", "z"])
print(np.sort(arr2))

['b' 'c' 'm' 's' 'x' 'z']


In [6]:
# 2-D Array
arr3 = np.array([[5,0,4],[1,9,3],[2,7,4]])
print(np.sort(arr3))

[[0 4 5]
 [1 3 9]
 [2 4 7]]


**filter() - getting some elements out of an existing array and creating a new array out of them**

In [7]:
arr4 = np.array(["b", "x", "c", "s", "m", "z"])
f = [True,False,False,True,True,False]
filtered_array = arr4[f]
print(filtered_array)
print(type(filtered_array))

['b' 's' 'm']
<class 'numpy.ndarray'>


**shuffle() - shuffle the elements randomly**

In [8]:
arr4 = np.array([1,2,3,4,5])
np.random.shuffle(arr4)
print(arr4)

[5 3 1 4 2]


**unique() - returns the unique elements in an array**

In [9]:
arr5 = np.array([1,2,3,4,2,5,2,5,7,6,2,7])
x = np.unique(arr5)
print(x)

[1 2 3 4 5 6 7]


In [10]:
arr5 = np.array([1,2,3,4,2,5,2,5,7,6,2,7])
x = np.unique(arr5, return_index = True, return_counts = True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 9, 8]), array([1, 4, 1, 1, 2, 1, 2]))


**resize() - converts 1-D array into 2-D array**

In [11]:
arr6 = np.array([1,2,3,4,5,6])
y = np.resize(arr6,(2,3)) # 1-D into 2-D
print(y)

[[1 2 3]
 [4 5 6]]


In [12]:
# Flatten - 2-D into 1-D
arr6 = np.array([1,2,3,4,5,6])
y = np.resize(arr6,(2,3)) # 1-D into 2-D
print(y)

[[1 2 3]
 [4 5 6]]


**flatten() - converts 2-D array into 1-D array**

In [13]:
print(y.flatten()) # 2-D into 1-D

[1 2 3 4 5 6]


In [14]:
print(y.flatten(order = "C")) # 'C' means to flatten in row-major

[1 2 3 4 5 6]


In [15]:
print(y.flatten(order = "F")) # 'F' means to flatten in column-major

[1 4 2 5 3 6]


In [16]:
print(np.ravel(y))

[1 2 3 4 5 6]
