## Indexing

In [1]:
import numpy as np

In [10]:
# 1-D Array
var = np.array([4,3,7,6])
# Indexes:      0,1,2,3
# -ve Indexing: -4,-3,-2,-1
print("Element at 1 :",var[1]) # var[1] - element of 1st index
print("Element at -2 :",var[-2]) # var[-2] - element of -2 index

Element at 1 : 3
Element at -2 : 7


In [11]:
#  2-D Array
var1 = np.array([[2,5,4], [9,6,4]])
print(var1)
print("Dimensions :", var1.ndim)
print("Element at (1,2) :",var1[1,2])

[[2 5 4]
 [9 6 4]]
Dimensions : 2
Element at (1,2) : 4


In [17]:
# 3-D Array
var2 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(var2)
print("Dimensions :", var2.ndim)
print("Element at (0,0,1) :",var2[0,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions : 3
Element at (0,0,1) : 2
