## Insert

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
i = np.insert(arr, 2, 18)
print(i)
j = np.insert(arr, (3,4), 24)
print(j)

[1 2 3 4]
[ 1  2 18  3  4]
[ 1  2  3 24  4 24]


In [3]:
arr1 = np.array([[1,2,3],[9,8,7]])
r = np.insert(arr1, 2, 6, axis=0) # row-wise
print(r,"\n")
c = np.insert(arr1, 2, 6, axis=1) #  column-wise
print(c)

[[1 2 3]
 [9 8 7]
 [6 6 6]] 

[[1 2 6 3]
 [9 8 6 7]]


In [4]:
m = np.insert(arr1, 1, [24,6,18], axis=0)
print(m,"\n")
n = np.insert(arr1, 3, [4,5], axis=1)
print(n)

[[ 1  2  3]
 [24  6 18]
 [ 9  8  7]] 

[[1 2 3 4]
 [9 8 7 5]]


In [5]:
# We can also use append() function to insert elements in an array
# But it inserts at the last position
arr = np.array([1,2,3,4])
print(arr)
i = np.append(arr,6)
print(i)

[1 2 3 4]
[1 2 3 4 6]


In [6]:
arr1 = np.array([[1,2,3],[9,8,7]])
m = np.append(arr1,[[24,6,18]], axis=0)
print(m)

[[ 1  2  3]
 [ 9  8  7]
 [24  6 18]]


## Delete

In [7]:
# delete(arrayName, index of element which is to be deleted)
arr2 = np.array([3,5,4,0])
print(arr2,"\n")
d = np.delete(arr2,1)
print(d)

[3 5 4 0] 

[3 4 0]
