## Iterating Numpy Arrays - using for loop

In [1]:
import numpy as np

In [2]:
# 1-D Array 
arr = np.array([3,5,4,2,7,9])
print(arr)
print()

for i in arr :
    print(i)

[3 5 4 2 7 9]

3
5
4
2
7
9


In [3]:
# 2-D Array
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print()

for i in arr1 :
    print(i)
print()

for j in arr1 :
    for k in j :
        print(k)
        

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [4]:
# 3-D Array
arr3 = np.array([[[1,2,3], [4,5,6]]])
print(arr3)
print("Dimensions :", arr3.ndim)
print()

for i in arr3 :
    for j in i :
        for k in j :
            print(k)

[[[1 2 3]
  [4 5 6]]]
Dimensions : 3

1
2
3
4
5
6


 ## Iterating Numpy Arrays - using nditer()

In [5]:
arr3 = np.array([[[1,2,3], [4,5,6]]])
print(arr3)
print("Dimensions :", arr3.ndim)
print()

for i in np.nditer(arr3) :
    print(i)

[[[1 2 3]
  [4 5 6]]]
Dimensions : 3

1
2
3
4
5
6


In [6]:
arr3 = np.array([[[1,2,3], [4,5,6]]])
print(arr3)
print("Dimensions :", arr3.ndim)
print()

for i in np.nditer(arr3, flags=['buffered'],op_dtypes=["S"]) :
    print(i)

[[[1 2 3]
  [4 5 6]]]
Dimensions : 3

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


In [7]:
# If we want indexes along with iteration
# ndenumerate()
arr3 = np.array([[[1,0,5,6,3], [2,7,0,8,4]]])
print(arr3)
print("Dimensions :", arr3.ndim)
print()

for i,d in np.ndenumerate(arr3) :
    print(i,d)

[[[1 0 5 6 3]
  [2 7 0 8 4]]]
Dimensions : 3

(0, 0, 0) 1
(0, 0, 1) 0
(0, 0, 2) 5
(0, 0, 3) 6
(0, 0, 4) 3
(0, 1, 0) 2
(0, 1, 1) 7
(0, 1, 2) 0
(0, 1, 3) 8
(0, 1, 4) 4
