**Joining Array means putting contents of two or more arrays in a single array**

In [1]:
import numpy as np

In [2]:
# For 1-D Array
arr1 = np.array([1,4,3,8])
arr2 = np.array([2,5,4,9])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 4 3 8 2 5 4 9]


In [3]:
# For 2-D Array
arr3 = np.array([[1,2],[3,4]])
print("Array 1 :\n",arr3)
print()

arr4 = np.array([[4,5],[6,7]])
print("Array 2 :\n",arr4)
print()

arr_hl = np.concatenate((arr3, arr4), axis=1)
print("Merged array along horizontal axis :\n",arr_hl)
print()

arr_vl = np.concatenate((arr3, arr4), axis=0)
print("Merged array along vertical axis :\n",arr_vl)

Array 1 :
 [[1 2]
 [3 4]]

Array 2 :
 [[4 5]
 [6 7]]

Merged array along horizontal axis :
 [[1 2 4 5]
 [3 4 6 7]]

Merged array along vertical axis :
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [4]:
# stack function 
arr5 = np.array([1,2,3,4])
arr6 = np.array([5,6,7,8])

arr_new = np.stack((arr5, arr6), axis = 1)
print(arr_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [5]:
# For accessing along row - hstack
arr_new = np.hstack((arr5, arr6))
print(arr_new)

[1 2 3 4 5 6 7 8]


In [6]:
# For accessing along column - vstack
arr_new = np.vstack((arr5, arr6))
print(arr_new)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# For accessing along height - dstack
arr_new = np.dstack((arr5, arr6))
print(arr_new)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
