## Matrix

In [1]:
import numpy as np

In [6]:
arr_matrix = np.matrix([[1,4,8],[5,9,0]])
print(arr_matrix)
print(type(arr_matrix))

[[1 4 8]
 [5 9 0]]
<class 'numpy.matrix'>


In [7]:
arr_array = np.array([[1,4,8],[5,9,0]])
print(arr_array)
print(type(arr_array))

[[1 4 8]
 [5 9 0]]
<class 'numpy.ndarray'>


**Arithmetic operations on matrix**

In [8]:
# Addition
arr1 = np.matrix([[2,4,6],[3,5,7]])
arr2 = np.matrix([[2,4,6],[3,5,7]])
print(arr1 + arr2)

[[ 4  8 12]
 [ 6 10 14]]


In [16]:
# Multiplication
arr1 = np.matrix([[2,4],[3,5]])
arr2 = np.matrix([[2,4],[3,5]])
print("By using multiplication sign\n",arr1 * arr2,"\n")
print("By using dot product\n",arr1.dot(arr2))

By using multiplication sign
 [[16 28]
 [21 37]] 

By using dot product
 [[16 28]
 [21 37]]


## Matrix Functions

**Transpose - rows into columns and vice versa**

In [21]:
arr = np.matrix([[1,0,4,5],[3,0,8,6]])
print(arr,"\n")
print(np.transpose(arr),"\n")
# We can also use arr.T
print(arr.T)

[[1 0 4 5]
 [3 0 8 6]] 

[[1 3]
 [0 0]
 [4 8]
 [5 6]] 

[[1 3]
 [0 0]
 [4 8]
 [5 6]]


**Swapaxes - rows into columns and vice versa**

In [23]:
arr = np.matrix([[1,0,4,5],[3,0,8,6]])
print(arr,"\n")
print(np.swapaxes(arr,0,1))

[[1 0 4 5]
 [3 0 8 6]] 

[[1 3]
 [0 0]
 [4 8]
 [5 6]]


In [25]:
sq_matrix = np.matrix([[1,7],[3,6]])
print(sq_matrix,"\n")
print(np.swapaxes(sq_matrix,1,0))

[[1 7]
 [3 6]] 

[[1 3]
 [7 6]]


**Inverse of a matrix**

In [27]:
arr3 = np.matrix([[1,2],[3,4]])
print(arr3,"\n")
print(np.linalg.inv(arr3)) # Inverse

[[1 2]
 [3 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]]


**Power of a matrix**

In [37]:
# np.linalg.matrix_power(arr, n)
# arr - array name
# n - n<0 or n=0 or n>0
# If n = 0, we get identity matrix
# If n > 0, the matrix is multiplied power no. of times
# If n < 0, we get the result - inverse * power 
A = np.matrix([[1,4],[2,9]])
print("A\n",A,"\n")
print("A^2\n",np.linalg.matrix_power(A,2),"\n") # n > 0
print("Identity matrix\n",np.linalg.matrix_power(A,0),"\n") # n = 0
print("Inverse * Power of matrix\n",np.linalg.matrix_power(A,-2)) # n < 0

A
 [[1 4]
 [2 9]] 

A^2
 [[ 9 40]
 [20 89]] 

Identity matrix
 [[1 0]
 [0 1]] 

Inverse * Power of matrix
 [[ 89. -40.]
 [-20.   9.]]


**Determinant of a matrix**

In [40]:
arr4 = np.matrix([[2,8],[4,9]])
print("Determinant\n",np.linalg.det(arr4))

Determinant
 -14.000000000000004
