## How to create multidimensional array

In [1]:
import numpy as np

In [2]:
# 1-D Array : []
arr1 = np.array([1,2,3,4])
print(arr1)
print(arr1.ndim) # ndim function gives the dimensions of array

[1 2 3 4]
1


In [3]:
# 2-D Array : [[]]
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [4]:
# 3-D Array : [[[]]]
arr3 = np.array([[[1,2,3,4], [5,6,7,8]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
3


**ndmin function**

In [5]:
# ndmin function : It creates the array of n dimensions, without need of putting n brackets
arrN = np.array([1, 2, 3, 4], ndmin = 10)
print(arrN)
print(arrN.ndim) # ndim function will print the array's dimension

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
