## Data Types

In [1]:
import numpy as np

var = np.array([1,2,3,4])
print("Data Type : ", var.dtype)

Data Type :  int64


In [2]:
var = np.array([1.0,2.4,3.7,4.9])
print("Data Type : ", var.dtype)

Data Type :  float64


In [3]:
var = np.array(["A", "M", "G", "J"])
print("Data Type : ", var.dtype)

Data Type :  <U1


In [4]:
var = np.array(["A", "M", "G", "J", 1, 2, 3, 4])
print("Data Type : ", var.dtype)

Data Type :  <U21


In [5]:
# Convert from one datatype to other
x = np.array([1,2,3,4])
print(x.dtype)

x = np.array([1,2,3,4], dtype = np.int8)
print(x.dtype)

int64
int8


In [6]:
x1 = np.array([1,2,3,4], dtype = "f")
print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4.]


In [7]:
x2 = np.array([1,2,3,4])
newx2 = np.float32(x2)

print("Data Type : ",x2.dtype)
print(x2)

print("Data Type : ", newx2.dtype)
print(newx2)

Data Type :  int64
[1 2 3 4]
Data Type :  float32
[1. 2. 3. 4.]


In [8]:
x2 = np.array([1,2,3,4])
newx2 = np.float32(x2)
new_one = np.int_(newx2)

print("Data Type : ",x2.dtype)
print(x2)

print("Data Type : ", newx2.dtype)
print(newx2)

print("Data Type : ", new_one.dtype)
print(new_one)

Data Type :  int64
[1 2 3 4]
Data Type :  float32
[1. 2. 3. 4.]
Data Type :  int64
[1 2 3 4]


In [10]:
x3 = np.array([5,6,7,8])
# astype() is also used to convert array of one data type to another
new = x3.astype(float)

print(x3)
print(new)

[5 6 7 8]
[5. 6. 7. 8.]
