# Numpy Axis

In [1]:
import numpy as np

In [2]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [3]:
arr = np.array(x)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
# Axis 0 counts in vertically downward direction
arr.sum(axis = 0)

array([12,  8,  9])

In [6]:
# Axis 1 counts in horizontal direction
arr.sum(axis = 1)

array([ 6, 15,  8])

In [7]:
arr.T # It will transpose the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
arr.flat # It will give an iterator

In [9]:
for item in arr.flat :
    print(item)

1
2
3
4
5
6
7
1
0


In [10]:
for item in arr :
    print(item)

[1 2 3]
[4 5 6]
[7 1 0]


In [11]:
arr.ndim # number of dimensions

2

In [12]:
arr.size # number of elements

9

In [13]:
arr.nbytes # total bytes consumed

72

In [14]:
one = np.array([1,3,4,245,2])

In [15]:
# argmax() : It gives the index of maximum element
one.argmax()

np.int64(3)

In [16]:
# argmin() : It gives the index of minimum element
one.argmin()

np.int64(0)

In [17]:
# argsort() : It gives the index of sorted array
one.argsort()

array([0, 4, 1, 2, 3])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [19]:
arr.argmin() # It first converts the 2-D array into 1-D array and then return the index of minimum element

np.int64(8)

In [20]:
arr.argmax() # It first converts the 2-D array into 1-D array and then return the index of maximum element

np.int64(6)

In [21]:
arr.argmax(axis = 0) # It gives the index of maximum in every column (axis = 0)

array([2, 1, 1])

In [22]:
arr.argmax(axis = 1) # It gives the index of maximum in every row (axis = 1)

array([2, 2, 0])

In [23]:
arr.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [24]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [25]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [26]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [27]:
arr.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

**Mathematical Operations in Numpy**

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
arr1 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [30]:
arr + arr1

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [31]:
# We can't perform mathematical operations in python list
[2, 4] + [1, 6]

[2, 4, 1, 6]

In [32]:
arr * arr1

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [33]:
arr - arr1

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [34]:
np.sqrt(arr) # square root of all elements

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [35]:
np.sum(arr) # sum of all elements

np.int64(29)

In [36]:
arr.max() # maximum element

np.int64(7)

In [37]:
arr.min() # minimum element

np.int64(0)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
np.where(arr>5) # It gives the index of elements greater than 5

(array([1, 2]), array([2, 0]))

In [40]:
type(np.where(arr>5))

tuple

In [41]:
np.count_nonzero(arr) # number of non zero elements

np.int64(8)

In [42]:
np.nonzero(arr) # It gives tuple for every axis for non zero elements

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [43]:
arr[1,2] = 0

In [44]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

**Proof - Numpy array takes less space than python list**

In [45]:
import sys

In [46]:
py_ar = [0,4,55,2]

In [47]:
np_ar = np.array(py_ar)

In [48]:
sys.getsizeof(1) * len(py_ar)

112

In [49]:
np_ar.itemsize * np_ar.size

32

In [50]:
np_ar.tolist() # It will give the python list of numpy array

[0, 4, 55, 2]