## Create array with random numbers

**rand() - used to generate a random value between 0 to 1**

In [3]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.07679578 0.3526551  0.77990238 0.21598131]


In [4]:
var1 = np.random.rand(2,5)
print(var1)

[[0.22808297 0.07335892 0.32628132 0.69830655 0.73107723]
 [0.36868861 0.61918556 0.84477181 0.89479469 0.94484141]]


**randn() - used to generate a random value close to zero, may return +ve and -ve numbers as well**

In [5]:
var2 = np.random.randn(5)
print(var2)

[-0.43857155 -0.85413257 -0.2888723  -0.89503156 -0.38825343]


**ranf() - for doing random sampling in numpy, returns an array of specified shape and fills it with random floats in the half open interval[0.0, 1.0)**

In [6]:
var3 = np.random.ranf(4)
print(var3)

[0.46548337 0.03210434 0.45833736 0.47257203]


**randint() - used to generate a random number between a given range**

In [8]:
# np.random.randint(min, max, total_values)
var4 = np.random.randint(5, 20, 5)
print(var4)

[14 19  8 19 14]
