**Shape**

In [1]:
import numpy as np

In [6]:
arr = np.array([[1,2,3,7], [4,7,8,0]])
print("Shape :",arr.shape)

Shape : (2, 4)


In [7]:
arr1 = np.array([1,2,3,4], ndmin = 4)
print(arr1)
print("Dimensions :",arr1.ndim)

print()
print("Shape :",arr1.shape)

[[[[1 2 3 4]]]]
Dimensions : 4

Shape : (1, 1, 1, 4)


**Reshape**

In [10]:
arr2 = np.array([1,2,3,4,5,6])
print(arr2)
print("Dimensions before reshaping :",arr2.ndim)
print()

s = arr2.reshape(3,2)
print(s)
print("Dimensions after reshaping :", s.ndim)

[1 2 3 4 5 6]
Dimensions before reshaping : 1

[[1 2]
 [3 4]
 [5 6]]
Dimensions after reshaping : 2


In [12]:
# arr2 = np.array([1,2,3,4,5,6])
# s = arr2.reshape(3,3)
# print(s)
# It will throw an error because we are reshaping into 3*3 = 9, but there are 6 elements in original array 

In [13]:
arr3 = np.array([1,4,6,3,0,9,2,1,8,6,3,2])
print(arr3)
print("Dimensions before reshaping :",arr3.ndim)
print()

s = arr3.reshape(2,3,2)
print(s)
print("Dimensions after reshaping :", s.ndim)

[1 4 6 3 0 9 2 1 8 6 3 2]
Dimensions before reshaping : 1

[[[1 4]
  [6 3]
  [0 9]]

 [[2 1]
  [8 6]
  [3 2]]]
Dimensions after reshaping : 3


In [14]:
arr3 = np.array([1,4,6,3,0,9,2,1,8,6,3,2])
print(arr3)
print("Dimensions before reshaping :",arr3.ndim)
print()

s = arr3.reshape(2,3,2)
print(s)
print("Dimensions after reshaping :", s.ndim)
print()

#reshape(-1) - reshapes to the original array
one = arr3.reshape(-1)
print(one)
print("Dimensions after again reshaping to the original array :",one.ndim)

[1 4 6 3 0 9 2 1 8 6 3 2]
Dimensions before reshaping : 1

[[[1 4]
  [6 3]
  [0 9]]

 [[2 1]
  [8 6]
  [3 2]]]
Dimensions after reshaping : 3

[1 4 6 3 0 9 2 1 8 6 3 2]
Dimensions after again reshaping to the original array : 1
