## Slicing

In [1]:
# x = [1,2,3,4,5]
# If I want numbers 2 to 4
# x[start : stop : step]

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7])
# Indexes :     0,1,2,3,4,5,6

print(arr)
print()
print("Elements from index 1 to index 4 :",arr[1:5])

# To get elements from a particular index to last
print("Elements from index 1 to last index :",arr[1:])

# To get elements from start to a particular index
print("Elements from index 0 to index 4 :",arr[:5])

# Get every 2nd element from index 1 to 5 (i.e., arr[1], arr[3], arr[5])
print("Elements from index 1 to 5 by a step of 2 :",arr[1:6:2]) # Slicing with a step of 2 starting at index 1 and going upto index 6(not included)

[1 2 3 4 5 6 7]

Elements from index 1 to index 4 : [2 3 4 5]
Elements from index 1 to last index : [2 3 4 5 6 7]
Elements from index 0 to index 4 : [1 2 3 4 5]
Elements from index 1 to 5 by a step of 2 : [2 4 6]


In [4]:
# Slicing in 2-D array
# arrayName[rowNo, columnNo from where you want the elements : columnNo to where you want the elements]

arr2 = np.array([[2,5,7,6,3],[1,7,0,3,5],[3,7,5,9,8]])
print(arr2)

# To get elements from 7 to 5 of 1st row
print("Elements of 1st row from column no 1 to 4 :",arr2[1,1:])
# We can also write it as - arr2[1,1:5]

[[2 5 7 6 3]
 [1 7 0 3 5]
 [3 7 5 9 8]]
Elements of 1st row from column no 1 to 4 : [7 0 3 5]
