**Splitting breaks one array into multiple**

In [1]:
import numpy as np

In [2]:
# 1-D Array
arr = np.array([1,2,3,4,5,6])
print("Original array :",arr)
print()

arr_split = np.array_split(arr, 3)
print("Splitted array :",arr_split)
print(type(arr_split),"\n")

print("Array at 0th index :",arr_split[0])

Original array : [1 2 3 4 5 6]

Splitted array : [array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'> 

Array at 0th index : [1 2]


In [3]:
# 2-D Array
arr1 = np.array([[1,4,6], [2,0,5], [3,7,2]])
print("Original Array\n",arr1,"\n")

arr1_split1 = np.array_split(arr1, 3)
print("Splitted Array in 3\n",arr1_split1,"\n")

arr1_split2 = np.array_split(arr1, 4)
print("Splitted Array in 4\n",arr1_split2,"\n")

arr1_split3 = np.array_split(arr1, 3, axis = 1)
print(arr1_split3,"\n")

arr1_split4 = np.array_split(arr1, 3, axis = 0)
print(arr1_split4)


Original Array
 [[1 4 6]
 [2 0 5]
 [3 7 2]] 

Splitted Array in 3
 [array([[1, 4, 6]]), array([[2, 0, 5]]), array([[3, 7, 2]])] 

Splitted Array in 4
 [array([[1, 4, 6]]), array([[2, 0, 5]]), array([[3, 7, 2]]), array([], shape=(0, 3), dtype=int64)] 

[array([[1],
       [2],
       [3]]), array([[4],
       [0],
       [7]]), array([[6],
       [5],
       [2]])] 

[array([[1, 4, 6]]), array([[2, 0, 5]]), array([[3, 7, 2]])]
